name: audio
channels:
  - defaults
dependencies:
  - pip
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - openssl=1.1.1w
  - python=3.10.4
  - python-dateutil=2.8.2
  - readline=8.1.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audeer==2.0.0
      - audformat==1.1.2
      - audinterface==1.1.0
      - audiofile==1.4.0
      - audioread==3.0.1
      - audmath==1.4.0
      - audobject==0.7.11
      - audresample==1.3.3
      - bottleneck==1.3.4
      - cachetools==5.3.2
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - colorcet==3.1.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - decorator==5.1.1
      - efficientnet-pytorch==0.7.1
      - ffmpeg==1.4
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.48.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.5.4
      - google-auth==2.27.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h5py==3.10.0
      - huggingface-hub==0.23.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - iso-639==0.4.5
      - iso3166==2.1.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - librosa==0.10.1
      - lightning==2.2.3
      - lightning-utilities==0.10.1
      - llvmlite==0.42.0
      - markdown==3.5.2
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.5
      - networkx==3.2.1
      - numba==0.59.0
      - numexpr==2.7.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.2.140
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opensmile==2.5.0
      - opt-einsum==3.3.0
      - oyaml==1.0
      - packaging==23.2
      - pandas==1.4.2
      - pillow==10.2.0
      - pip==24.0
      - platformdirs==4.2.0
      - pooch==1.8.0
      - protobuf==4.25.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyparsing==3.1.1
      - pytorch-lightning==2.2.0.post0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2024.4.28
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - soundfile==0.12.1
      - soxr==0.3.7
      - sympy==1.12
      - timm
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0.post1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - termcolor==2.4.0
      - tf-slim==1.1.0
      - threadpoolctl==3.2.0
      - tokenizers==0.19.1
      - torch==2.2.0
      - torchvision==0.17.0
      - torchaudio==2.2.0
      - torchlibrosa==0.1.0
      - torchmetrics==1.3.1
      - tqdm==4.66.2
      - transformers==4.40.1
      - triton==2.2.0
      - typing-extensions==4.9.0
      - urllib3==2.2.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - yarl==1.9.4
      - zipp==3.17.0

